@extends('layouts.app')
@section('title', 'Profil Akademik Saya - SDM Villa Merah')
@section('page_title', 'Profil Akademik Saya')
@section('content')
<div class="teacher-profile-page">
    <form method="POST" action="{{ route('teacher.profile.update') }}" class="academic-form-card">@csrf @method('PUT')<div class="form-card-heading"><div><h4>Data Akademik Pengajar</h4><small>Lengkapi data akademik dan sertifikasi agar profil dapat dipantau secara akurat.</small></div><span class="readonly-badge"><i class="bi bi-lock"></i> Identitas tersimpan</span></div><div class="row g-3"><div class="col-md-6"><label class="form-label">NIP</label><input class="form-control" value="{{ $employee?->nip ?: 'Belum diatur' }}" readonly></div><div class="col-md-6"><label class="form-label">Nama Lengkap</label><input class="form-control" value="{{ $employee?->nama ?: 'Belum diatur' }}" readonly></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" value="{{ $employee?->email ?: 'Belum diatur' }}" readonly></div><div class="col-md-6"><label class="form-label">Telepon / WhatsApp <span>*</span></label><input name="telepon" class="form-control" value="{{ $employee?->telepon }}" required></div><div class="col-md-6"><label class="form-label">NIK / KTP</label><input name="ktp" class="form-control" value="{{ $employee?->ktp }}" maxlength="16"></div><div class="col-md-6"><label class="form-label">Divisi Akademik</label><input name="divisi_akademik" class="form-control" value="{{ $employee?->divisi_akademik }}" placeholder="Contoh: Seni Rupa"></div><div class="col-md-6"><label class="form-label">Kampus Asal</label><input name="kampus_asal" class="form-control" value="{{ $employee?->kampus_asal }}" placeholder="Nama institusi pendidikan"></div><div class="col-md-6"><label class="form-label">Dokumen Pelatihan</label><input name="dokumen_pelatihan" class="form-control" value="{{ $employee?->dokumen_pelatihan }}" placeholder="Nama dokumen/sertifikat pelatihan"></div><div class="col-md-6"><label class="form-label">Nomor Sertifikat</label><input name="nomor_sertifikat" class="form-control" value="{{ $employee?->nomor_sertifikat }}"></div></div><div class="academic-note"><i class="bi bi-info-circle"></i> Data yang ditampilkan berasal dari profil employee yang sedang login.</div><div class="form-actions"><a href="{{ route('teacher.dashboard') }}" class="back-link">Kembali</a><button class="save-button"><i class="bi bi-check2"></i> Simpan Profil Akademik</button></div></form>
    <div class="academic-extra">@include('shared.profile.academic-competencies', ['competencies' => $competencies, 'portfolios' => $portfolios])</div>
</div>
@endsection
@push('styles')
<style>
.teacher-profile-page{max-width:1180px;margin:0 auto;color:#14243b}.profile-intro{display:flex;justify-content:space-between;align-items:center;padding:1.35rem 1.5rem;margin-bottom:1.25rem;border-radius:12px;background:linear-gradient(110deg,#1551d1,#087e76);color:#fff;box-shadow:0 5px 15px #123b6620}.profile-intro span{font-size:.65rem;letter-spacing:.11em;opacity:.75}.profile-intro h2{margin:.35rem 0 .25rem;font-size:1.45rem}.profile-intro p{margin:0;font-size:.8rem;opacity:.88}.profile-intro>i{font-size:3rem;opacity:.35;margin-right:1rem}.academic-form-card{padding:1.5rem;border:1px solid #e5ebf0;border-radius:12px;background:#fff;box-shadow:0 4px 16px #1737530b}.form-card-heading{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:1.25rem;padding-bottom:1rem;border-bottom:1px solid #edf1f4}.form-card-heading h4{margin:0 0 .25rem;font-size:1.05rem}.form-card-heading small{color:#8492a2;font-size:.72rem}.readonly-badge{padding:.35rem .55rem;border-radius:6px;background:#f1f6ff;color:#4376bd;font-size:.66rem}.readonly-badge i{margin-right:.2rem}.form-label{color:#526274;font-size:.78rem;font-weight:600}.form-label span{color:#dc3545}.form-control{min-height:42px;border-color:#dfe7ed;border-radius:8px;font-size:.83rem;color:#26384e}.form-control:focus{border-color:#6199e5;box-shadow:0 0 0 .2rem #6199e522}.form-control[readonly]{background:#f7f9fb;color:#6b7b8c}.form-actions{display:flex;justify-content:flex-end;align-items:center;gap:1rem;margin-top:1.5rem;padding-top:1rem;border-top:1px solid #edf1f4}.back-link{color:#6d7d8c;text-decoration:none;font-size:.78rem}.save-button{border:0;border-radius:8px;padding:.65rem 1rem;background:#1769dc;color:#fff;font-size:.78rem;box-shadow:0 4px 10px #1769dc2b}.save-button:hover{background:#1258bd}.academic-extra{margin-top:1.25rem}@media(max-width:767px){.profile-intro{display:block}.profile-intro>i{display:none}.academic-form-card{padding:1rem}.form-card-heading{display:block}.readonly-badge{display:inline-block;margin-top:.7rem}.form-actions{justify-content:space-between}}
</style>
@endpush
