<?php
$out = __DIR__.'/../docs/Laporan-Poin-Penting-SI-Villa-Merah.docx';
$paras = [
 ['LAPORAN POIN PENTING - SISTEM INFORMASI VILLA MERAH','title'],
 ['Ringkasan kebutuhan pengembangan, arsitektur, keamanan, dan operasional','sub'],
 ['1. Gambaran Umum Sistem','h1'],
 ['Sistem Informasi Villa Merah adalah aplikasi pengelolaan sumber daya manusia berbasis Laravel dengan role-based access control. Sistem memusatkan data akun, pegawai, pengajar, dokumen, kompetensi, pengumuman, audit aktivitas, dan pencadangan data.','p'],
 ['2. Peran dan Hak Akses','h1'],
 ['Super Admin: administrasi akun, pegawai, pengajar, pengumuman, backup, log aktivitas, dan biodata sendiri.','li'],
 ['Karyawan: self-service profil dan dokumen sendiri.','li'], ['Pengajar: profil, kampus asal, kompetensi, dan dokumen sendiri.','li'], ['Karyawan & Pengajar: profil struktural dan akademik dalam satu akun.','li'], ['Direksi: ringkasan organisasi dan direktori read-only.','li'],
 ['3. Modul Aplikasi','h1'],
 ['Autentikasi dan manajemen akun; dashboard per role; biodata self-service; manajemen dokumen; master spesialisasi; pengumuman internal; monitoring Direksi; impor/ekspor Excel; log aktivitas; backup ZIP JSON.','p'],
 ['4. Data, Relasi, dan Kardinalitas','h1'],
 ['Entitas inti: users, employees, employee_documents, specializations, announcements, activity_logs, payroll, salary_components, dan contract_histories. Users memiliki satu role; pegawai memiliki banyak dokumen dan relasi HR berbasis NIP; activity_logs terhubung opsional ke users.','p'],
 ['5. Alur Proses','h1'], ['Login -> autentikasi -> middleware role -> dashboard sesuai role.','li'], ['Pegawai memilih Edit Profil -> mengisi data -> Simpan Perubahan Profil -> data tersimpan dan ditampilkan kembali dari database.','li'], ['Super Admin mengisi Biodata Saya dengan alur yang sama.','li'], ['Super Admin menjalankan Backup -> snapshot tabel -> ZIP private -> unduhan terautentikasi.','li'], ['Request terautentikasi dicatat middleware LogActivity.','li'],
 ['6. Keamanan dan Audit','h1'], ['Role middleware membatasi route; staf hanya mengubah profil sendiri; Direksi tidak memiliki route CRUD; form memakai CSRF dan validasi; impor Excel transaksional; backup hanya untuk Super Admin; aktivitas dicatat pada activity_logs.','p'],
 ['7. Backup, Restore, API, dan Teknologi','h1'], ['Backup menghasilkan arsip ZIP berisi manifest dan JSON tabel inti. Restore dilakukan setelah verifikasi arsip, backup database aktif, validasi struktur, dan uji integritas. Endpoint internal Laravel memakai session authentication, CSRF, dan role middleware. Stack: PHP 8.3, Laravel 13, Blade, Bootstrap/CSS, Eloquent, PhpSpreadsheet, dan ZipArchive.','p'],
 ['8. Checklist Laporan','h1'], ['ERD dan kardinalitas; DFD dan flow proses; use case dan hak akses; struktur tabel; modul aplikasi; enterprise architecture; API; security checklist; backup dan restore; fitur aplikasi.','p'],
 ['Sumber: Daftar Isi dan Poin Penting dalam Dokumen Pengembangan SISTEM INFORMASI VILLA MERAH.pdf serta dokumentasi proyek pada folder docs.','sub']
];
$esc=fn($s)=>htmlspecialchars($s,ENT_XML1|ENT_COMPAT,'UTF-8'); $body='';
foreach($paras as [$text,$type]){ $style=$type==='title'?'Title':($type==='h1'?'Heading1':'Normal'); $prefix=$type==='li'?'• ':''; $body.='<w:p><w:pPr><w:pStyle w:val="'.$style.'"/></w:pPr><w:r><w:t xml:space="preserve">'.$esc($prefix.$text).'</w:t></w:r></w:p>'; }
$files=['[Content_Types].xml'=>'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>', '_rels/.rels'=>'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>', 'word/_rels/document.xml.rels'=>'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>', 'word/styles.xml'=>'<?xml version="1.0" encoding="UTF-8"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:rFonts w:ascii="Aptos"/><w:sz w:val="20"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:b/><w:color w:val="17365D"/><w:sz w:val="40"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="Heading 1"/><w:rPr><w:b/><w:color w:val="1F4E79"/><w:sz w:val="28"/></w:rPr></w:style></w:styles>', 'word/document.xml'=>'<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'.$body.'<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1080" w:right="1224" w:bottom="1080" w:left="1224"/></w:sectPr></w:body></w:document>'];
$zip=new ZipArchive(); $zip->open($out,ZipArchive::CREATE|ZipArchive::OVERWRITE); foreach($files as $name=>$content)$zip->addFromString($name,$content); $zip->close(); echo $out;
