<?php
$out=__DIR__.'/../docs/Daftar-Komponen-Teknologi-SI-SDM.docx';
$items=[
['DAFTAR KOMPONEN TEKNOLOGI','title'],['Sistem Informasi Sumber Daya Manusia (SI SDM)','sub'],
['Tujuan dan Ruang Lingkup','h1'],['Dokumen ini menyajikan komponen teknologi yang membentuk SI SDM berdasarkan struktur kode, konfigurasi, dan dokumentasi proyek yang tersedia.','p'],
['1. Platform Aplikasi','h1'],['PHP 8.4 - runtime bahasa pemrograman.','li'],['Laravel Framework 13.8 - framework utama dan fondasi MVC.','li'],['Composer dan composer.lock - manajemen dependensi backend.','li'],
['2. Antarmuka dan Asset Frontend','h1'],['Laravel Blade - template halaman login, dashboard, profil, kontrak, dokumen, dan admin.','li'],['CSS dan Tailwind CSS - styling, layout, warna, responsivitas, dan komponen visual.','li'],['Vite dan laravel-vite-plugin - kompilasi serta pengelolaan asset CSS/JavaScript.','li'],
['3. Backend dan Arsitektur Aplikasi','h1'],['Laravel MVC - pemisahan route/middleware, controller, model Eloquent, dan view.','li'],['routes/web.php - endpoint internal berbasis session Laravel dan CSRF.','li'],['Auth dan role middleware - pembatasan akses super_admin, direksi, karyawan, pengajar, dan karyawan_pengajar.','li'],['Controller/service - use case pegawai, dokumen, kontrak, payroll, pengumuman, backup, dan laporan.','li'],['Eloquent ORM - akses dan operasi CRUD pada database relasional.','li'],
['4. Data dan Penyimpanan','h1'],['Database relasional - users, employees, specializations, employee_documents, announcements, activity_logs, payroll, komponen gaji, dan riwayat kontrak.','li'],['Laravel private disk - penyimpanan berkas pegawai dan backup yang memerlukan akses terlindungi.','li'],['ZipArchive - membuat backup ZIP berisi snapshot JSON tabel.','li'],['PhpSpreadsheet - impor dan ekspor data XLSX.','li'],
['5. Modul Fungsional','h1'],['Autentikasi dan manajemen akun: login, logout, reset password, status akun, dan impersonasi.','li'],['Manajemen SDM: data karyawan/pengajar, status aktif, template impor, dan ekspor.','li'],['Profil, dokumen, kompetensi, dan portofolio: self-service sesuai role dan kepemilikan data.','li'],['Kontrak dan payroll: monitoring kontrak, perpanjangan, riwayat, ringkasan, dan data kompensasi.','li'],['Pengumuman dan audit: announcements, LogActivity, dan activity_logs.','li'],
['6. Keamanan','h1'],['Session authentication dan role-based access control.','li'],['CSRF token serta validasi server-side untuk request mutasi.','li'],['Direksi bersifat read-only; backup hanya dapat diunduh Super Admin melalui storage private.','li'],['Aktivitas request mencatat user, route, metode, IP, waktu, dan deskripsi.','li'],
['7. Pengembangan dan Operasi','h1'],['PHPUnit, tests/Unit, dan tests/Feature - pengujian model, fitur, serta integrasi HTTP.','li'],['Laravel Pint - konsistensi format kode PHP.','li'],['npm run build dan deploy.sh - build asset production dan penyiapan deployment.','li'],
['8. Alur Keterkaitan','h1'],['Browser -> Blade/CSS -> route dan middleware -> controller/service -> Eloquent -> database/private storage -> view, JSON, XLSX, atau ZIP.','p'],['Catatan: proyek belum memiliki routes/api.php atau autentikasi Bearer token; endpoint saat ini merupakan endpoint web internal berbasis session Laravel.','p'],
['Sumber Acuan','h1'],['docs/arsitektur-teknologi.md, docs/arsitektur-aplikasi.md, docs/arsitektur-data.md, docs/security.md, docs/api.md, composer.json, package.json, dan docs/sistem-sdm-final.md.','p']
];
$esc=fn($s)=>htmlspecialchars($s,ENT_XML1|ENT_COMPAT,'UTF-8');$body='';
foreach($items as [$t,$ty]){$st=$ty==='title'?'Title':($ty==='h1'?'Heading1':'Normal');$pre=$ty==='li'?'• ':'';$body.='<w:p><w:pPr><w:pStyle w:val="'.$st.'"/></w:pPr><w:r><w:t xml:space="preserve">'.$esc($pre.$t).'</w:t></w:r></w:p>';}
$files=['[Content_Types].xml'=>'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>','_rels/.rels'=>'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>','word/_rels/document.xml.rels'=>'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>','word/styles.xml'=>'<?xml version="1.0"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:rFonts w:ascii="Calibri"/><w:sz w:val="22"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:b/><w:color w:val="0B2545"/><w:sz w:val="48"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="Heading 1"/><w:rPr><w:b/><w:color w:val="2E74B5"/><w:sz w:val="32"/></w:rPr></w:style></w:styles>','word/document.xml'=>'<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'.$body.'<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>'];
$z=new ZipArchive();$z->open($out,ZipArchive::CREATE|ZipArchive::OVERWRITE);foreach($files as $n=>$c)$z->addFromString($n,$c);$z->close();echo $out;

